### PR TITLE
Practice task #1

### PR DESCRIPTION
**Pull request by AleksMaksymenko**

### CODE REVIEW

**Comment by MikeKurshakov** [comment]
Be careful with cache settings
image

**Comment by MikeKurshakov** [comment]
You should execute the test from your laptop and not inside VM where Blog is installed
image

Test with non `1` - RAMPUP_TIME and LOOP_COUNT

**Comment by MikeKurshakov** [comment]
Use meaningful names for the tread group.(Like Simple script etc.)
image

**Comment by MikeKurshakov** [comment]
Delete Protocol and Domain, and try to use HTTP Request Defaults
image

**Comment by MikeKurshakov** [comment]
In HTTP Request Defaults configure parallel downloads
image

**Comment by MikeKurshakov** [comment]
Delete all unused elements
image

**Comment by AleksMaksymenko** [comment]
> Be careful with cache settings image

that checkbox should be marked, right?

**Pull request merged**
